import {
    LayoutDashboard,
    Truck,
    Users,
    Package,
    HardHat,
    UserCog,
    Landmark,
    Settings,
    // Fournisseur
    Contact,
    ClipboardList,
    Banknote,
    FileInput,
    CreditCard,
    Scale,
    ScrollText,
    // Client
    ContactRound,
    FileCheck,
    FileSignature,
    CircleDollarSign,
    Receipt,
    Wallet,
    // Stock
    ArrowLeftRight,
    Factory,
    ClipboardCheck,
    PackageMinus,
    PackageCheck,
    PackageOpen,
    Boxes,
    // Chantiers
    MapPin,
    TrendingDown,
    // Personnel
    BadgeCheck,
    CalendarCheck,
    // Monétaire
    Coins,
    Vault,
    FileText,
    Warehouse,
} from 'lucide-react';

export const navigation = [
    {
        id: 'dashboard',
        label: 'Tableau de Bord',
        icon: LayoutDashboard,
        perm: 'dashboard.view',
        to: '/',
    },
    {
        id: 'fournisseurs',
        label: 'Fournisseur',
        icon: Truck,
        perm: 'fournisseurs.view',
        children: [
            { to: '/fournisseurs/fiches', label: 'Fiche Fournisseur', icon: Contact },
            { to: '/fournisseurs/bons-achats', label: 'Bon Achats', icon: ClipboardList },
            { to: '/fournisseurs/bons-commande', label: 'Bon de Commande', icon: ClipboardCheck },
            { to: '/fournisseurs/reglements-achats', label: 'Règlement Achats', icon: Banknote },
            { to: '/fournisseurs/balance', label: 'Balance', icon: Scale },
            { to: '/fournisseurs/releve-compte', label: 'Relevé Compte', icon: ScrollText },
        ],
    },
    {
        id: 'clients',
        label: 'Client',
        icon: Users,
        perm: 'clients.view',
        children: [
            { to: '/clients/fiches', label: 'Fiche Client', icon: ContactRound },
            { to: '/clients/bons-de-vente', label: 'Bon de Vente', icon: ClipboardList },
            { to: '/clients/reglements-vente', label: 'Règlement Client', icon: CircleDollarSign },
            { to: '/clients/balance', label: 'Balance', icon: Scale },
            { to: '/clients/releve-compte', label: 'Relevé Compte', icon: ScrollText },
        ],
    },
    {
        id: 'facturation',
        label: 'Facturation',
        icon: FileText,
        perm: 'factures_clients.view',
        children: [
            { to: '/facturation/factures-achats', label: 'Facture Achats', icon: FileInput },
            { to: '/facturation/depot-a', label: 'Depot A', icon: Warehouse, disabled: true },
            { to: '/facturation/depot-b', label: 'Depot B', icon: Warehouse, disabled: true },
            { to: '/facturation/reglement', label: 'Règlement', icon: CreditCard },
            { to: '/facturation/factures-ventes', label: 'Facture des Ventes', icon: Receipt },
            { to: '/facturation/reglements', label: 'Règlements', icon: Wallet },
            { to: '/facturation/balance', label: 'Balances Factures Clients', icon: Scale },
        ],
    },
    {
        id: 'stock',
        label: 'Stock',
        icon: Package,
        perm: 'stock.view',
        children: [
            {
                label: 'Etat Stock',
                icon: ClipboardList,
                children: [
                    { to: '/stock/etat-stock/cru', label: 'Cru', icon: PackageOpen },
                    { to: '/stock/etat-stock/fini', label: 'Fini', icon: PackageCheck },
                    { to: '/stock/etat-stock/divers', label: 'Divers', icon: Boxes },
                ],
            },
            { to: '/stock/bon-production', label: 'Bon Production', icon: Factory },
            { to: '/stock/bon-sortie', label: 'Bon Sortie', icon: PackageMinus },
            { to: '/stock/produit-fini', label: 'Produit Fini', icon: PackageCheck },
            { to: '/stock/mouvements', label: 'Mouvement Stock', icon: ArrowLeftRight },
        ],
    },
    {
        id: 'chantiers',
        label: 'Chantiers',
        icon: HardHat,
        perm: 'chantiers.view',
        disabled: true,
        children: [
            { to: '/chantiers/carte', label: 'Carte Chantiers', icon: MapPin },
            { to: '/clients/devis', label: 'Devis', icon: FileSignature },
            { to: '/clients/bons-vente', label: "Bon D'Execution", icon: FileCheck },
            { to: '/chantiers/suivi-depenses', label: 'Suivi Dépenses', icon: TrendingDown },
        ],
    },
    {
        id: 'personnel',
        label: 'Personnel',
        icon: BadgeCheck,
        perm: 'personnel.view',
        children: [
            { to: '/personnel/fiches', label: 'Fiche Personnel', icon: Contact },
            { to: '/personnel/etat-paiement', label: 'État Paiement', icon: CalendarCheck },
        ],
    },
    {
        id: 'monetaire',
        label: 'Suivi Monétaire',
        icon: Landmark,
        perm: 'reglements.view',
        children: [
            { to: '/monetaire/transactions', label: 'Transaction et Charges', icon: ArrowLeftRight },
            { to: '/monetaire/charges', label: 'Charge', icon: Wallet },
            { to: '/monetaire/rapports', label: 'Rapports', icon: FileText },
            { to: '/monetaire/salaires', label: 'Salaire', icon: Coins },
            { to: '/monetaire/tresorerie', label: 'Trésorerie', icon: Vault },
        ],
    },
    {
        id: 'configuration',
        label: 'Configuration',
        icon: Settings,
        perm: 'utilisateurs.view',
        children: [
            { to: '/configuration/utilisateurs', label: 'Utilisateur', icon: UserCog },
        ],
    },
];
